Repository christopherkeim/christopherkeim-xyz, pull requests merged in 2023-11, with the labels that each got.

#6 Kenson/implement fetch
  .env.local.example
  app/api/crypto/predict/route.ts
  components/Projects/Crypto/CryptoHero.tsx
  components/Projects/Crypto/PredictionContainer.tsx
  components/Projects/Crypto/PredictionForm.tsx
  components/Projects/Crypto/PredictionResult.tsx
Labels: enhancement

#7 Minimum Viable Crypto Documentation
  components/Projects/Crypto/PaperHeader.tsx
  components/Projects/Crypto/ResearchPaper.tsx
  public/images/BTC-USD_candle_plot.png
  public/images/BTC_modeling.png
  public/images/ETH-USD_candle_plot.png
  public/images/ETH_modeling.png
  public/images/continuous_delivery.png
  public/images/continuous_deployment.png
  public/images/feature_engineering.png
  public/images/prediction.png
  public/images/project_overview.png
  public/images/training.png
Labels: documentation, enhancement

#8 Updates for multiple sections.
  components/Projects/Crypto/ResearchPaper.tsx
Labels: documentation, enhancement

#9 Grammar and clarity edits.
  components/Projects/Crypto/ResearchPaper.tsx
Labels: documentation

#10 Set skill width for mobile view
  components/Widgets/WidgetSkills.tsx
Labels: bug

#11 Desktop and mobile styling for circular profile.
  app/page.tsx
  package-lock.json
  package.json
  prettier.config.js
Labels: enhancement

#12 Kenson/style research paper
  app/projects/crypto/page.tsx
  components/Projects/Crypto/PaperImage.tsx
  components/Projects/Crypto/ResearchPaper.tsx
Labels: enhancement

#14 Kenson/cleanup research paper
  app/projects/crypto/page.tsx
  components/Projects/Crypto/PaperParagraph.tsx
  components/Projects/Crypto/ResearchOrderedList.tsx
Labels: bug

#15 Kenson/prediction container
  components/Projects/Crypto/CryptoHero.tsx
  components/Projects/Crypto/PredictionForm.tsx
  components/Projects/Crypto/PredictionResult.tsx
  components/Projects/Crypto/PredictionRow.tsx
  components/Projects/Crypto/PredictionTable.tsx
Labels: enhancement

#17 Update Prediction Result Table Formatting
  components/Projects/Crypto/PredictionResult.tsx
  components/Projects/Crypto/PredictionRow.tsx
  components/Projects/Crypto/PredictionTable.tsx
Labels: enhancement

#20 Dynamic Point and Line Colors for Prediction Graph
  components/Projects/Crypto/PredictionForm.tsx
  components/Projects/Crypto/PredictionResult.tsx
  components/Projects/Crypto/PredictionTable.tsx
  package-lock.json
  package.json
Labels: enhancement

#21 Kenson/transfer contact form
  .env.local.example
  app/api/contact/route.ts
  app/contact/page.tsx
  app/layout.tsx
  components/Projects/Crypto/CryptoHero.tsx
  components/Projects/Crypto/PaperHeader.tsx
  components/Projects/Crypto/PredictionResult.tsx
  package-lock.json
  package.json
  tailwind.config.ts
Labels: enhancement
